version: "3.8"

services:
    web:
        env_file: ./frontend/.env
        stdin_open: true
        build:
            context: ./frontend
        ports: 
            - "3000:3000"
        depends_on:
            - backend

    backend:
        env_file: ./backend/.env
        build:
            context: ./backend
        ports:
            - "5000:5000"
        